# This script parses the .csv file(s) in /Input with respect to the needs of "Group14's algorithm"

import csv
import sys
import trigonometryAlgorithm
import numpy as np


# TODO --> Rename this script to "Reciever.py"


# Argument 1: The detection module {HSV, Machine-Learning}
detectionModule = sys.argv[1]
# csvFile1 = "Algorithmic Services/Input/detected-cone-positions.csv"
# csvFile2 = "./Algorithmic Services/Input/detected-cone-positions2.csv"
i = 1


# Function:
#   - Parses the CSV file that is generated from Yolov8 (ML = Machine Learning)
#   - Deletes the redundant characters that were generated by the PyTorch ML-Model
if detectionModule == "ML":
    with open("Algorithmic Services/Input/detected-cone-positions.csv", "r") as myFile:

        myDictionary = {"right": [-1, -1], "left": [-1, -1]}
        reader = csv.reader(myFile, delimiter="\t")

        for i, line in enumerate(reader):
            testRow = 'line[{}] = {}'.format(i, line)

            sub_list = ["tensor", "(", ")", "]", "[", "'"]
            currentLine = str(line)

            for sub in sub_list:
                currentLine = currentLine.replace(sub, "")

            # lineValues = [x, y, w, h] of the detected box
            lineValues = currentLine.split(",") # PREVIOUS --> WORKS
            # lineValues = np.array(currentLine.split(","))

            x = np.array(lineValues)

            if lineValues[0] == "X-Position":
                continue

            # The closest cones for each side (left, right) will always have the smallest Y value
            # since it is closest to the center of the car that is in the bottom of the screen
            minlLeftY = float("inf")
            minRightY = float("inf")


            # ["right"] = [x, y]
            # ["left"] = [x, y]
            # myDictionary = {"right": [-1, -1], "left": [-1, -1]}


            # TODO --> Write each row to the new .csv file and do control check that the number of lines satifies this formula:
            # numLines = numOriginalCsvLines * 2   <=>   numLines = 366 * 2 = 732

            # filename = "./Algorithmic Services/Input/filtered-ML-Output.csv"
            fields = ['X-Position', 'Y-Position', 'Width', 'Height']
            newFrameField = ['----- NEW FRAME -----']

            with open("./Algorithmic Services/Input/detected-cone-positions2.csv", 'w') as csvfile:
                # creating a csv writer object
                csvwriter = csv.writer(csvfile)
                csvwriter.writerow(fields)

                # If new frame
                if len(lineValues) != 4:
                    print("----- NEW FRAME -----")
                    trigonometryAlgorithm.analyzeCurrentFrame(myDictionary, i) # Perform the algorithmic calculation based on the current values
                    myDictionary = {"right": [-1, -1], "left": [-1, -1]} # Reset dictionary
                    i += 1
                else:
                    # y = x.astype(np.float64)
                    # print(f"My G --> {y}")
                    
                    cLD = x.astype(np.float64) # cLD = Current Csv Line Dimensions
                    csvwriter.writerow("9")

                    # If x value of the detected cone is within left field
                    if cLD[0] >= 50 and cLD[0] <= 250:
                        if cLD[1] < minlLeftY:
                            minlLeftY = cLD[1]
                            myDictionary["left"] = [cLD[0], cLD[1]]

                        # print(f"Left   -->   {lineValues}")

                        
                    elif cLD[0] >= 250 and cLD[0] <= 650:
                        if cLD[1] < minRightY:
                            minRightY = cLD[1]
                            myDictionary["right"] = [cLD[0], cLD[1]]

                        # print(f"Right   -->    {lineValues}")


# Parse the CSV file that is generated from HSV
else:
    pass



# Once the CSV's content has been parsed, we store the calculated results so that Visualization Service can use it
trigonometryAlgorithm.storeCalculatedResults()